# -*- coding: utf-8 -*-
"""dma_crossover.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qvBSSCC9ZkruGAGTeVuDiSWfAIn9os3G
"""



import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt

df=yf.download('AAPL', start='2019-01-01')

df

df['MA50'] = df['Close'].rolling(50).mean()
df['MA200'] = df['Close'].rolling(200).mean()

df

df = df.dropna()

df = df[['Close', 'MA50', 'MA200']]

df

Buy = []
Sell = []
for i in range(len(df)):
  if df.MA50.iloc[i] > df.MA200.iloc[i] \
  and df.MA50.iloc[i-1] < df.MA200.iloc[i-1]:
      Buy.append(i)
  elif df.MA50.iloc[i] < df.MA200.iloc[i] \
  and df.MA50.iloc[i-1] > df.MA200.iloc[i-1]:
      Sell.append(i)

Buy

Sell

plt.figure(figsize=(12,5))
plt.plot(df['Close'], label= 'Asset price', c='blue', alpha= 0.5)
plt.plot(df['MA50'], label= 'MA50', c='k', alpha = 0.9)
plt.plot(df['MA200'], label= 'MA200', c='magenta', alpha = 0.9)
plt.scatter(df.iloc[Buy].index,df.iloc[Buy]['Close'],marker='^', color='g', s=100)
plt.scatter(df.iloc[Sell].index,df.iloc[Sell]['Close'],marker='v', color='r', s=200)
plt.legend()
plt.show()